# These are supported funding model platforms

github: [hzoo, tatianamac, martinklepsch]
patreon: particleconnect
open_collective: particleconnect
ko_fi: # Replace with a single Ko-fi username
tidelift: 
custom: # Replace with a single custom sponsorship URL
